### ISSUE TITLE
实验结果相关

### ISSUE THREAD

**Issue by LuckyyySTA** [orangetwo/ernie-csc#1]
请问您尝试过在SIGHAN数据集上的finetune实验吗？表现如何？我在paddle版本的官方代码上进行实验，发现效果甚至没有论文中的ERNIE的结果好

**Comment by orangetwo** [comment]
他没有公布预训练模型 效果比不上论文里的效果 也正常吧

init ***@***.***>于2021年12月20日 周一上午11:27写道：

**Comment by anshen666** [comment]
> 请问您尝试过在SIGHAN数据集上的finetune实验吗？表现如何？我在paddle版本的官方代码上进行实验，发现效果甚至没有论文中的ERNIE的结果好

你好，我在运行[ernie-csc](https://github.com/orangetwo/ernie-csc)这个代码的时候，报了这个错 OSError: Error no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index', 'flax_model.msgpack'] found in directory ernie or from_tf and from_flax set to False. 请问你知道要怎么解决吗？ 或者您方便留个联系方式吗
